name: Deploy Static Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug Environment
        run: |
          echo "GitHub Context:"
          echo "  Repository: ${{ github.repository }}"
          echo "  Ref: ${{ github.ref }}"
          echo "  SHA: ${{ github.sha }}"
          echo "Runner Context:"
          echo "  OS: ${{ runner.os }}"
          echo "  Arch: ${{ runner.arch }}"
          echo "Job Context:"
          echo "  Job ID: ${{ job.id }}"
          echo "  Job Status: ${{ job.status }}"
      
      - name: Debug Secrets
        run: |
          echo "SERVER_IP is set: ${{ secrets.SERVER_IP != '' }}"
          echo "SERVER_USER is set: ${{ secrets.SERVER_USER != '' }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          echo "First line of SSH_PRIVATE_KEY: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1)"
          echo "Last line of SSH_PRIVATE_KEY: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -n 1)"
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Debug SSH Agent
        run: |
          ssh-add -l
          echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
          echo "SSH_AGENT_PID: $SSH_AGENT_PID"
      
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} exit
        continue-on-error: true
      
      - name: Deploy with rsync
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/sat20-website/ --exclude .git --exclude .github
        continue-on-error: true
      
      - name: Deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "Deployment successful!"
          else
            echo "Deployment failed. Check the logs for more information."
          fi

      - name: Debug Final State
        if: always()
        run: |
          echo "Final Job Status: ${{ job.status }}"
          echo "Steps Context:"
          echo "${{ toJson(steps) }}"